### PR TITLE
Reduces a bit the size of expressions AST

### PR DESCRIPTION
**Pull request by andremm**
This pull request makes two things: reduces a bit the size of expressions AST and fixes some small issues with operators associativity in the `lua-parser.lua` example.

For instance, `return 2^3+1` was generating the following AST:
```lua
rule='chunk',
{
         rule='block',
         {
                  rule='retstat',
                  'return',
                  {
                           rule='explist',
                           {
                                    rule='exp',
                                    {
                                             rule='expOR',
                                             {
                                                      rule='expAND',
                                                      {
                                                               rule='expREL',
                                                               {
                                                                        rule='expBIT',
                                                                        {
                                                                                 rule='expCAT',
                                                                                 {
                                                                                          rule='expADD',
                                                                                          {
                                                                                                   rule='expMUL',
                                                                                                   {
                                                                                                            rule='expUNA',
                                                                                                            {
                                                                                                                     rule='expPOW',
                                                                                                                     {
                                                                                                                              rule='expTokens',
                                                                                                                              {
                                                                                                                                       rule='number',
                                                                                                                                       {
                                                                                                                                                rule='INT',
                                                                                                                                                '2',
                                                                                                                                       },
                                                                                                                              },
                                                                                                                     },
                                                                                                                     {
                                                                                                                              rule='operatorPower',
                                                                                                                              '^',
                                                                                                                     },
                                                                                                                     {
                                                                                                                              rule='expUNA',
                                                                                                                              {
                                                                                                                                       rule='expPOW',
                                                                                                                                       {
                                                                                                                                                rule='expTokens',
                                                                                                                                                {
                                                                                                                                                         rule='number',
                                                                                                                                                         {
                                                                                                                                                                  rule='INT',
                                                                                                                                                                  '3',
                                                                                                                                                         },
                                                                                                                                                },
                                                                                                                                       },
                                                                                                                              },
                                                                                                                     },
                                                                                                            },
                                                                                                   },
                                                                                          },
                                                                                          {
                                                                                                   rule='operatorAddSub',
                                                                                                   '+',
                                                                                          },
                                                                                          {
                                                                                                   rule='expMUL',
                                                                                                   {
                                                                                                            rule='expUNA',
                                                                                                            {
                                                                                                                     rule='expPOW',
                                                                                                                     {
                                                                                                                              rule='expTokens',
                                                                                                                              {
                                                                                                                                       rule='number',
                                                                                                                                       {
                                                                                                                                                rule='INT',
                                                                                                                                                '1',
                                                                                                                                       },
                                                                                                                              },
                                                                                                                     },
                                                                                                            },
                                                                                                   },
                                                                                          },
                                                                                 },
                                                                        },
                                                               },
                                                      },
                                             },
                                    },
                           },
                  },
         },
},
```

After faking a `fold` with repetition and removing extra nodes I got the following AST:

```lua
rule='chunk',
{
         rule='block',
         {
                  rule='retstat',
                  'return',
                  {
                           rule='explist',
                           {
                                    rule='exp',
                                    {
                                             rule='exp',
                                             {
                                                      rule='exp',
                                                      {
                                                               rule='exp',
                                                               {
                                                                        rule='expTokens',
                                                                        {
                                                                                 rule='number',
                                                                                 {
                                                                                          rule='INT',
                                                                                          '2',
                                                                                 },
                                                                        },
                                                               },
                                                               {
                                                                        rule='operatorPower',
                                                                        '^',
                                                               },
                                                               {
                                                                        rule='exp',
                                                                        {
                                                                                 rule='expTokens',
                                                                                 {
                                                                                          rule='number',
                                                                                          {
                                                                                                   rule='INT',
                                                                                                   '3',
                                                                                          },
                                                                                 },
                                                                        },
                                                               },
                                                      },
                                             },
                                             {
                                                      rule='operatorAddSub',
                                                      '+',
                                             },
                                             {
                                                      rule='expTokens',
                                                      {
                                                               rule='number',
                                                               {
                                                                        rule='INT',
                                                                        '1',
                                                               },
                                                      },
                                             },
                                    },
                           },
                  },
         },
},
```

Regarding operators associativity, you were using repetition for some rules that should associate to the right:
```lua
...
expCAT		<- 	expADD (operatorStrcat expADD^ErrConcatExpr)* -- associate to the right
...
expPOW		<- 	expTokens (operatorPower expUNA^ErrPowExpr)* -- associate to the right
...
```
So I just changed them to only use right recursion.
```lua
...
expCAT		<- 	(expADD (operatorStrcat expCAT^ErrConcatExpr)?) -> fixexp
...
expPOW		<- 	(expTokens (operatorPower expUNA^ErrPowExpr)?) -> fixexp
...
```

### CODE REVIEW

**Review by vsbenas — CHANGES_REQUESTED** [review]
Really great work!! Line 16 should be changed to 
```lua
elseif exp[1] then
```
because the next line throws an error when a label is thrown in lua-parser-tests.lua:
lua: ./lua-parser.lua:17: attempt to index field '?' (a nil value)

**Review by vsbenas — APPROVED** [review]

**Comment by andremm** [comment]
> Really great work!! Line 16 should be changed to

Thanks for applying my PR and fixing my mistake. I haven't gone through tests, sorry, and going back and forth between C and Lua sometimes makes my eyes not see this kind of silly mistake. :)

@vsbenas  In fact, I believe changing
```lua
elseif exp[1] then
```
to only
```lua
else
```
should also work.

**Comment by vsbenas** [comment]
Not so much a mistake, as a special case for when we have a partial AST due
to errors in the input, thanks for the contribution.

2017-09-19 10:56 GMT-04:00 Andre Murbach Maidl <notifications@github.com>:

**Comment by vsbenas** [comment]
> @vsbenas In fact, I believe changing
> 
> elseif exp[1] then
> to only
> 
> else
> should also work.

@andremm 
it was `else`
in your code, and that threw the runtime error, because the next line accesses `exp[1].rule` but `exp[1]` could be nil.

**Comment by andremm** [comment]
> @andremm
> it was else
> in your code, and that threw the runtime error, because the next line accesses exp[1].rule but exp[1] could be nil.

Yeah, I realize now. :) Thanks!

**Pull request merged**
